# Contains lists of apt packages for each stage (build|release) and arch or accelerator.
apt:
  pkgs:
    build_common:
      - ccache
      - curl
      - git
      - gnupg
      - libopenblas-dev
      - ninja-build
      - procps
      - python3-pip
      - rename
      - vim
      - wget
      - clang-format
      - clang-{{ clang_version }}
      - gcc-11
      - g++-11
      - lcov
      - less

    build_aarch64:
      - scons

    release_common:
      - curl
      - git
      - gnupg
      - libgomp1
      - patch
      - vim

  # Specify objects with string fields `url` and `keyring`.
  # The keyring path should start with /usr/share/keyrings/ for debian and ubuntu.
  signing_keys:
    - url: https://apt.llvm.org/llvm-snapshot.gpg.key
      keyring: /usr/share/keyrings/llvm.pgp

  repos:
    # signed-by path should match the corresponding keyring path above.
    - "deb [signed-by=/usr/share/keyrings/llvm.pgp] http://apt.llvm.org/{{ llvm_debian_repo }}/ llvm-toolchain-{{ llvm_debian_repo }}-{{ clang_version }} main"
    - "deb-src [signed-by=/usr/share/keyrings/llvm.pgp] http://apt.llvm.org/{{ llvm_debian_repo }}/ llvm-toolchain-{{ llvm_debian_repo }}-{{ clang_version }} main"
