pip:
  pkgs:
    build_common:
      - astunparse
      - cffi
      - cloud-tpu-client
      - cmake
      - coverage
      - dataclasses
      - expecttest==0.1.3
      - future
      - git-archive-all
      - google-api-python-client
      - google-cloud-storage
      - hypothesis
      - lark-parser
      - ninja
      - numpy
      - oauth2client
      - pyyaml
      - requests
      - setuptools
      - six
      - tensorboard
      - tensorboardX
      - tqdm
      - typing
      - typing_extensions

    build_amd64:
      - mkl
      - mkl-include

    build_aarch64:

    release_common:
      - numpy
      - pyyaml
      - mkl
      - mkl-include

    release_tpu:
      - torch_xla[tpuvm]

  pkgs_nodeps:
    release_common:
      - torchvision
      - pillow
