- name: "Install build dependencies"
  hosts: localhost
  connection: local
  vars_prompt:
    - name: stage
      prompt: "Stage (accepted values: build, release)"
      private: false

    - name: arch
      prompt: "Complete steps for a given architecture (accepted values: aarch64, amd64)"
      private: false

    - name: accelerator
      prompt: "Accelerator type (accepted values: tpu, cuda)"
      private: false

  pre_tasks:
    - name: "Include vars from config/{{ item }}"
      ansible.builtin.include_vars:
        file: "config/{{ item }}"
      loop:
        # vars.yaml should be the first as other config files depend on it.
        - vars.yaml
        - apt.yaml
        - pip.yaml
        - env.yaml

  roles:
    - bazel

    - role: install_deps
      vars:
        apt_keys: "{{ apt.signing_keys }}"

        # If a variable (like `apt.pkgs.common`) is defined, but not set to
        # anything it cannot be concatenated with a list.
        # Use `v | default([], true)` to set `v` to an empty array if it evaluates to false.
        # See https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.default.
        apt_pkgs: "{{
            apt.pkgs[stage + '_common'] | default([], true) +
              apt.pkgs[stage + '_' + arch] | default([], true) +
              apt.pkgs[stage + '_' + accelerator] | default([], true)
          }}"

        apt_repos: "{{ apt.repos }}"

        pip_pkgs: "{{
            pip.pkgs[stage + '_common'] | default([], true) +
            pip.pkgs[stage + '_' + arch] | default([], true) +
            pip.pkgs[stage + '_' + accelerator] | default([], true)
          }}"

        pip_pkgs_nodeps: "{{
            pip.pkgs_nodeps[stage + '_common'] | default([], true) +
            pip.pkgs_nodeps[stage + '_' + arch] | default([], true) +
            pip.pkgs_nodeps[stage + '_' + accelerator] | default([], true)
          }}"

    - role: fetch_srcs
      vars:
        src_root: "/src"
        pytorch_git_rev: 5e9fa0a8fc87f9a626f144bb5527da0426ac384b
        xla_git_rev: 6acc0c9cc7aa0738ec792ddd4780d14f66d6bd8c

    - role: build_srcs
      vars:
        src_root: "/src"
        env_vars: "{{
            build_env.common | default({}, true) |
            combine(build_env[arch] | default({}, true)) |
            combine(build_env[accelerator] | default({}, true))
          }}"

    - role: configure_env
      vars:
        env_vars: "{{
            runtime_env.common | default({}, true) |
            combine(runtime_env[arch] | default({}, true)) |
            combine(runtime_env[accelerator] | default({}, true))
          }}"
      when: stage == "release"
