name: Set up PyTorch/XLA
inputs:
    wheels-artifact:
        type: string
        description: |
            Artifact containing `torch` (cpu) and `torch-xla` wheels to install
runs:
    using: "composite"
    steps:
        # See https://github.com/actions/checkout/issues/1014#issuecomment-1906802802
        - name: Clean up workspace
          shell: bash
          run: |
              ls -la
              rm -rvf ${GITHUB_WORKSPACE}/*

        - name: Setup gcloud
          shell: bash
          run: |
              echo "${GCLOUD_SERVICE_KEY}" > /tmp/default_credentials.json
              echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/default_credentials.json" >> $GITHUB_ENV
          # GCLOUD_SERVICE_KEY needs to be set from the outside because for some
          # reason composite actions don't support secrets.
          # https://docs.github.com/en/actions/using-workflows/avoiding-duplication
          if: ${{ env.GCLOUD_SERVICE_KEY }}

        # Checkout PyTorch/XLA first, so that we have access to the PyTorch commit pin
        # that we should use when checking out PyTorch.
        - name: Checkout PyTorch/XLA Repo
          uses: actions/checkout@v4
          with:
              path: xla

        # Retrieve the actual PyTorch commit.
        - id: torch
          name: Get PyTorch Commit Pin
          shell: bash
          run: |
              COMMIT=$(cat "xla/.torch_commit")
              echo "commit=$COMMIT" >> $GITHUB_OUTPUT

        # Checkout PyTorch using the retrieved PyTorch commit.
        - name: Checkout PyTorch Repo
          uses: actions/checkout@v4
          with:
              repository: pytorch/pytorch
              path: pytorch
              ref: ${{ steps.torch.outputs.commit }}
              submodules: recursive

        # After checking out both PyTorch and PyTorch/XLA, we need to move PyTorch/XLA
        # to the PyTorch directory.
        - name: Move PyTorch/XLA Inside PyTorch
          shell: bash
          run: mv -v xla/ pytorch/

        - name: Fetch PyTorch/XLA packages
          uses: actions/download-artifact@v5
          with:
              name: ${{ inputs.wheels-artifact }}
              path: /tmp/wheels/
          if: ${{ inputs.wheels-artifact }}

        - name: Install wheels
          shell: bash
          run: |
              pip install /tmp/wheels/*.whl

              echo "Import check..."
              python -c "import torch_xla"
          if: ${{ inputs.wheels-artifact }}
