# Contains lists of apt packages for each stage (build|release) and arch or accelerator.
apt:
  pkgs:
    build_common:
      - ccache
      - curl
      - git
      - gnupg
      - libopenblas-dev
      - ninja-build
      - procps
      - python3-pip
      - rename
      - vim
      - wget

    build_cuda:
      - "cuda-libraries-{{ cuda_version | replace('.', '-')   }}"
      - "cuda-toolkit-{{ cuda_version | replace('.', '-')   }}"
      - "cuda-minimal-build-{{ cuda_version | replace('.', '-')   }}"
      - "{{ cuda_deps['libcudnn'][cuda_version] }}"
      - "{{ cuda_deps['libcudnn-dev'][cuda_version] }}"

    build_amd64:
      - "clang-{{ clang_version }}"

    build_aarch64:
      - scons
      - gcc-10
      - g++-10

    release_common:
      - curl
      - git
      - gnupg
      - google-cloud-cli
      - libgomp1
      - libopenblas-base
      - patch

    release_cuda:
      - "cuda-libraries-{{ cuda_version | replace('.', '-')   }}"
      - "cuda-minimal-build-{{ cuda_version | replace('.', '-')   }}"
      - "{{ cuda_deps['libcudnn'][cuda_version] }}"

  # Specify objects with string fields `url` and `keyring`.
  # The keyring path should start with /usr/share/keyrings/ for debian and ubuntu.
  signing_keys:
    - url: https://apt.llvm.org/llvm-snapshot.gpg.key
      keyring: /usr/share/keyrings/llvm.pgp
    - url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      keyring: /usr/share/keyrings/cloud.google.gpg
    - url: "https://developer.download.nvidia.com/compute/cuda/repos/{{ cuda_repo }}/x86_64/3bf863cc.pub"
      keyring: /usr/share/keyrings/cuda.pgp

  repos:
    # signed-by path should match the corresponding keyring path above.
    - "deb [signed-by=/usr/share/keyrings/llvm.pgp] http://apt.llvm.org/{{ llvm_debian_repo }}/ llvm-toolchain-{{ llvm_debian_repo }}-{{ clang_version }} main"
    - "deb-src [signed-by=/usr/share/keyrings/llvm.pgp] http://apt.llvm.org/{{ llvm_debian_repo }}/ llvm-toolchain-{{ llvm_debian_repo }}-{{ clang_version }} main"
    - "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    - "deb [signed-by=/usr/share/keyrings/cuda.pgp] https://developer.download.nvidia.com/compute/cuda/repos/{{ cuda_repo }}/x86_64/ /"