- name: "Check that various import statements work"
  ansible.builtin.command:
    cmd: "{{ item }}"
  loop:
    - python -c "import torchgen"
    - python -c "import torch"
    - python -c "import torch_xla"
    - python -c "import torch_xla.core.xla_model"
