- name: Build XLA computation client library
  ansible.builtin.command:
    cmd: bash build_torch_xla_libs.sh -O -D_GLIBCXX_USE_CXX11_ABI=1
    chdir: "{{ (src_root, 'pytorch/xla') | path_join }}"

- name: Build PyTorch/XLA
  ansible.builtin.command:
    cmd: python setup.py bdist_wheel
    chdir: "{{ (src_root, 'pytorch/xla') | path_join }}"
  environment:
    PYTORCH_BUILD_VERSION: "{{ package_version }}"
    TPUVM_MODE: "{{ tpu_vm }}"
    XLA_CUDA: "{{ cuda }}"
    TF_CUDA_COMPUTE_CAPABILITIES: "{{ tf_cuda_compute_capabilities }}"
    BUILD_CPP_TESTS: "{{ build_cpp_tests }}"
