- name: "Install build dependencies"
  hosts: 127.0.0.1
  connection: local
  vars_prompt:
    - name: stage_env
      prompt: "Stage and env type (possible options: build_aarch64, build_amd64)"
      private: false

  pre_tasks:
    - name: "Include vars from config/{{ item }}"
      ansible.builtin.include_vars:
        file: "config/{{ item }}"
      loop:
        # vars.yaml should be the first as other config files depend on it.
        - vars.yaml
        - apt.yaml
        - pip.yaml

  roles:
    - bazel

    - role: install_deps
      vars:
        apt_keys: "{{ apt.signing_keys }}"

        # If a variable (like `apt.pkgs.common`) is defined, but not set to
        # anything it cannot be concatenated with a list.
        # Use `v | default([], true)` to set `v` to an empty array if it evaluates to false.
        # See https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.default.
        apt_pkgs: "{{
            apt.pkgs.common | default([], true) + apt.pkgs[stage_env] | default([], true)
          }}"

        apt_repos: "{{ apt.repos }}"

        pip_pkgs: "{{
            pip.pkgs.common | default([], true) + pip.pkgs[stage_env] | default([], true)
          }}"

        pip_pkgs_nodeps: "{{
            pip.pkgs_nodeps.common | default([], true) + pip.pkgs_nodeps[stage_env] | default([], true)
          }}"

    - role: fetch_srcs
      vars:
        src_root: "/src"

    - role: build_srcs
      vars:
        src_root: "/src"
