- name: "Install build dependencies"
  hosts: 127.0.0.1
  connection: local
  vars_prompt:
    - name: stage_env
      prompt: "Stage and env type (possible options: build_aarch64, build_amd64)"
      private: false

  pre_tasks:
    - name: Include vars from config/common.yaml
      ansible.builtin.include_vars:
        file: config/common.yaml

    - name: Include vars from config/apt.yaml
      ansible.builtin.include_vars:
        file: config/apt.yaml

  roles:
    - bazel

    - role: init_repos
      vars:
        apt_keys: "{{ apt.signing_keys }}"

    - role: build_deps
      vars:
        apt_pkgs: "{{ apt.pkgs[stage_env] }}"
        apt_repos: "{{ apt.repos }}"
