- name: Install required apt packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: "{{ 60 * 60 * 12 }}" # 12h, set in seconds
  loop: "{{ apt_packages }}"
