- name: Build PyTorch
  ansible.builtin.command:
    cmd: python setup.py bdist_wheel
    chdir: "{{ (src_root, 'pytorch') | path_join }}"
    creates: "{{ (src_root, 'pytorch/dist/*.whl') | path_join }}"
  # Set `USE_CUDA=0` as PyTorch cannot be used with GPU in eager and XLA mode.
  environment: "{{ env_vars | combine({'USE_CUDA': 0}) }}"

- name: Find PyTorch *.whl files in pytorch/dist
  ansible.builtin.find:
    path: "{{ (src_root, 'pytorch/dist') | path_join }}"
    pattern: "*.whl"
  register: pytorch_wheels

- name: Install PyTorch wheels
  ansible.builtin.pip:
    name: "{{ pytorch_wheels.files | map(attribute='path') }}"
    state: "forcereinstall"

- name: Build XLA computation client library
  ansible.builtin.command:
    cmd: bash build_torch_xla_libs.sh -O -D_GLIBCXX_USE_CXX11_ABI=1
    chdir: "{{ (src_root, 'pytorch/xla') | path_join }}"
  environment: "{{ env_vars }}"

- name: Build PyTorch/XLA
  ansible.builtin.command:
    cmd: python setup.py bdist_wheel
    chdir: "{{ (src_root, 'pytorch/xla') | path_join }}"
  environment: "{{ env_vars }}"

- name: Find XLA *.whl files in pytorch/xla/dist
  ansible.builtin.find:
    path: "{{ (src_root, 'pytorch/xla/dist') | path_join }}"
    pattern: "*.whl"
  register: xla_wheels

- name: Install XLA wheels
  ansible.builtin.pip:
    name: "{{ xla_wheels.files | map(attribute='path') }}"
    state: "forcereinstall"

- name: Create a temp directory for collecting wheels
  ansible.builtin.file:
    path: /tmp/staging-wheels
    state: directory
    mode: '0755'

- name: Create /dist directory for exported wheels
  ansible.builtin.file:
    path: /dist
    state: directory
    mode: '0755'

- name: Rename and append +YYYYMMDD suffix to nightly wheels
  ansible.builtin.shell: |
    pushd /tmp/staging-wheels
    cp {{ item.dir }}/*.whl .
    rename -v "s/^{{ item.prefix }}-(.*?)-cp/{{ item.prefix }}-nightly-cp/" *.whl
    mv /tmp/staging-wheels/* /dist/
    popd

    rename -v "s/^{{ item.prefix }}-(.*?)-cp/{{ item.prefix }}-nightly+$(date -u +%Y%m%d)-cp/" *.whl
  args:
    executable: /bin/bash
    chdir: "{{ item.dir }}"
  loop:
    - { dir: "{{ (src_root, 'pytorch/dist') | path_join }}", prefix: "torch" }
    - { dir: "{{ (src_root, 'pytorch/xla/dist') | path_join }}", prefix: "torch_xla" }
  when: nightly_release

- name: Copy wheels to /dist
  ansible.builtin.shell: "cp {{ item }}/*.whl /dist"
  args:
    executable: /bin/bash
  loop:
    - "{{ (src_root, 'pytorch/dist') | path_join }}"
    - "{{ (src_root, 'pytorch/xla/dist') | path_join }}"

- name: Delete temp directory
  ansible.builtin.file:
    path: /tmp/staging-wheels
    state: absent
    mode: '0755'

- name: "Tests"
  include_tasks: tests.yaml
  tags:
    - tests
