on:
  pull_request:
    branches:
      - master
      - r[0-9]+.[0-9]+
    paths:
      - 'experimental/torch_xla2/**'
  push:
    branches:
      - master
      - r[0-9]+.[0-9]+
    paths:
      - 'experimental/torch_xla2/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:
  torchxla2-cpu:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            experimental/torch_xla2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        shell: bash
        working-directory: experimental/torch_xla2
        run: |
          pip install -r test-requirements.txt
          pip install -e .[cpu]
          pip install tensorflow-cpu  # for TF integrations tests
      - name: Run tests
        working-directory: experimental/torch_xla2
        shell: bash
        run: |
          pytest test/
          XLA_FLAGS=--xla_force_host_platform_device_count=4 pytest -n 0 test_dist/
