name: torchax
on:
  pull_request:
    branches:
      - master
      - r[0-9]+.[0-9]+
  push:
    branches:
      - master
      - r[0-9]+.[0-9]+
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:
  torchax-cpu:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            torchax
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        shell: bash
        working-directory: torchax
        run: |
          pip install -r test-requirements.txt
          pip install -e .[cpu]
      - name: Run tests
        working-directory: torchax
        shell: bash
        run: |
          export JAX_PLATFORMS=cpu
          # Find all Python test files recursively
          find ./test -name "test_*.py" -type f | while IFS= read -r test_file; do
            # Skip tests with known issues
            if [[ "$test_file" == *"test_tf_integration.py"* ]]; then
              echo "Skipping ${test_file}. TODO(https://github.com/pytorch/xla/issues/8770): Investigate"
              continue
            fi
            echo "Running tests for $test_file"
            pytest "$test_file"
          done
          # Run distributed tests.
          XLA_FLAGS=--xla_force_host_platform_device_count=4 pytest -n 0 test_dist/
